from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class PromotionResult:
    promotion_brief_md: str
    readme_draft_md: str
    project_page_copy_md: str
    ppt_outline_md: str
    artifact_count: int


class PromotionWriter:
    """Create conservative dissemination drafts from verified artifacts."""

    def draft_promotion(self, task_input: dict[str, Any], output_dir: Path | str) -> PromotionResult:
        output_path = Path(output_dir)
        report = self.read_text(output_path / "final_report.md") or self.read_text(output_path / "report.md")
        verification = self.read_json(output_path / "verification_result.json")
        final_qa = self.read_json(output_path / "final_qa_result.json")
        status = self.status_line(verification, final_qa)

        brief_path = output_path / "promotion_brief.md"
        readme_path = output_path / "readme_draft.md"
        page_path = output_path / "project_page_copy.md"
        ppt_path = output_path / "ppt_outline.md"
        brief_path.write_text(self.render_brief(report, status), encoding="utf-8")
        readme_path.write_text(self.render_readme(status), encoding="utf-8")
        page_path.write_text(self.render_project_page(status), encoding="utf-8")
        ppt_path.write_text(self.render_ppt_outline(report, status), encoding="utf-8")
        return PromotionResult(
            promotion_brief_md=str(brief_path),
            readme_draft_md=str(readme_path),
            project_page_copy_md=str(page_path),
            ppt_outline_md=str(ppt_path),
            artifact_count=4,
        )

    @staticmethod
    def read_text(path: Path) -> str:
        return path.read_text(encoding="utf-8") if path.exists() else ""

    @staticmethod
    def read_json(path: Path) -> dict[str, Any]:
        if not path.exists():
            return {}
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}

    @staticmethod
    def status_line(verification: dict[str, Any], final_qa: dict[str, Any]) -> str:
        if final_qa:
            return f"Final QA export_allowed={str(bool(final_qa.get('export_allowed'))).lower()}."
        if verification:
            return f"Verification publication_ready={str(bool(verification.get('publication_ready'))).lower()}."
        return "Verification artifacts were not available when this promotion draft was generated."

    @staticmethod
    def excerpt(report: str, limit: int = 1200) -> str:
        text = " ".join(line.strip() for line in report.splitlines() if line.strip())
        return text[:limit] if text else "No report text was available."

    def render_brief(self, report: str, status: str) -> str:
        return "\n".join(
            [
                "# Promotion Brief",
                "",
                f"- verification_status: {status}",
                "- claim_policy: Do not include unverified performance, novelty, or SOTA claims.",
                "",
                "## Short Description",
                "",
                self.excerpt(report, 700),
                "",
            ]
        )

    @staticmethod
    def render_readme(status: str) -> str:
        return "\n".join(
            [
                "# README Draft",
                "",
                "This project draft was generated from Auto Research artifacts.",
                "",
                "## Verification Status",
                "",
                status,
                "",
                "## Usage Notes",
                "",
                "- Replace this draft with project-specific installation and run commands.",
                "- Keep unsupported scientific claims out of public copy.",
                "",
            ]
        )

    @staticmethod
    def render_project_page(status: str) -> str:
        return "\n".join(
            [
                "# Project Page Copy",
                "",
                "## One-Line Summary",
                "",
                "Evidence-grounded research artifacts generated by an Auto Research pipeline.",
                "",
                "## Verification Status",
                "",
                status,
                "",
                "## Caution",
                "",
                "This copy should be reviewed before public dissemination.",
                "",
            ]
        )

    def render_ppt_outline(self, report: str, status: str) -> str:
        return "\n".join(
            [
                "# PPT Outline",
                "",
                "## Slide 1: Research Scope",
                "",
                "- State the research topic and evidence policy.",
                "",
                "## Slide 2: Evidence Summary",
                "",
                f"- {self.excerpt(report, 400)}",
                "",
                "## Slide 3: Methods and Comparisons",
                "",
                "- Use `literature_matrix.csv` and `benchmark_matrix.csv` when available.",
                "",
                "## Slide 4: Verification Status",
                "",
                f"- {status}",
                "",
                "## Slide 5: Next Steps",
                "",
                "- Add full-text evidence, run experiments, and resolve QA blockers before strong claims.",
                "",
            ]
        )
